### ISSUE TITLE
downloading error of gee data

### ISSUE THREAD

**Issue by a14en9** [krisrs1128/glacier_mapping#85]
Hi Kris,

When downloading data from GEE using "landsat-7-2005-hkh" under the ee_code folder, the following error occurred.

**Error: Exported bands must have compatible data types; found inconsistent types: Float64 and Float32.**

Hope you can help me to address it.

Best wishes,
Oliver

**Comment by Aryal007** [comment]
Hello cvhabitat, I wasn't able to reproduce this issue in google earthengine code editor. Could you be more specific on which line is giving you the error?

**Comment by a14en9** [comment]
Hi Aryal,

The problem occurs when I clicked the **RUN** button under **Tasks**. Consequently, the files in tiff format will not appear in google OneDrive. I am new to this field. So I don’t know if this description is clear, or if it’s only me who has encountered this kind of problem.

Thanks,
Oliver

**Comment by Aryal007** [comment]
Hi Oliver, 

I don't seem to be able to recreate the problem. However, if you are still having the issue, please try the python based api for google earth engine to download images for training in the gee_python_api branch. Let me know if this solves your issue.

https://github.com/krisrs1128/glacier_mapping/blob/gee_python_api/scripts/ee_code/get_training_images.py

Regards,
Bibek

**Comment by a14en9** [comment]
Hi Bibek,

Many thanks for helping on this problem. I haven't solved the problem but I tried to download the preprocessed data from [Here](http://lila.science/datasets/hkh-glacier-mapping). I'll try to find the solution for this issue.

Thanks for your reply.
Oliver
